# Generated by Django 2.2.12 on 2020-10-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, unique=True)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('has_projector', models.NullBooleanField(default='No data')),
            ],
        ),
    ]
