# Generated by Django 2.2.12 on 2020-10-17 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfMan', '0003_auto_20201015_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 17, 14, 49, 47, 517787)),
        ),
    ]
